name: example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  fragua_custom_widgets:
    path: ../
  photo_view: ^0.14.0  # Para hacer zoom a las imágenes
  syncfusion_flutter_pdfviewer: ^26.2.9  # Para visualizar archivos PDF en todos lados
  flutter_pdfview: ^1.2.7 # Para visualizar archivos PDF en Web
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/